### ISSUE TITLE
readme is very bad

### ISSUE THREAD

**Issue by maddox05** [maddox05/image-editor-lite#1]
someone update the readme to look better and describe and explain the project.

**Comment by vijay-varadarajan** [comment]
I'll be glad to update your readme and make it look better. Please assign this to me

**Comment by maddox05** [comment]
assigned.

**Comment by vijay-varadarajan** [comment]
Hi, thank you for assigning me this issue
I have already completed the task and sent you a pull request.
Please review that and let me know if you need any further changes to be made

**Comment by vijay-varadarajan** [comment]
Hi, Thank you for accepting my changes to your readme. 

Please consider adding the 'hacktoberfest' label to your repository's About section and the 'hacktoberfest-accepted' label to my pull request, so that this is counted towards the hacktoberfest.
